name: Publish Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install DocFX
      run: dotnet tool install -g docfx

    - name: Generate Documentation
      run: |
        docfx init -q
        docfx build

    - name: Generate Class Diagram
      run: |
        echo 'classDiagram
        class AppSettings {
          +string Environment
          +string ApiBaseUrl
          +Initialize(string, string)
          +GetSummary() string
        }' > docs/diagram.md

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site
        publish_branch: gh-pages